### ISSUE TITLE
Переработать FeatureToggle

### ISSUE THREAD

**Issue by Vadim4016** [surfstudio/debug-screen-ios#25]
Как работает сейчас: 
- FeatureToggleActionsProvider предоставляет список FeatureToggleModel и выступает обработчиком событий. 

Минусы: 
- Перегружен ответственностью.
- Разрывает контекст FeatureToggle, где в одном методе мы определяем ее состояние, а в другом методе ее поведение. 

Предлагаю: 
- FeatureToggleModel переработать в protocol
- Методы поведения определить во FeatureToggleModel
- Удалить метод обработки события у FeatureToggleActionsProvider
- Экран, работающий с FeatureToggleModel, напрямую взаимодействует с ней.

Итог: 
- Таким образом мы не разрываем поведение и представление фича-тогла.
- Пользователь может сам настраивать желаемое поведение конкретного фича-тогла. 
- Дополнительно можно определить часто используемые реализации в библиотеке.  (Пример с UserDefaults)

Пример протокола
```swift
public protocol FeatureToggle {
    /// Заголовок
    var title: String { get }
    /// Состояние свитчера 
    var isEnabled: Bool { get set }
}
```
Пример реализации FeatureToggle, которая хранит свое состояние в UserDefaults и имеет дефолтное значение.
```swift
public struct UserDefaultsFeatureToggle: FeatureToggle {
    public let title: String

    public var isEnabled: Bool {
        get {
             let storedValue = storage.object(forKey: key) as? Bool
             return storedValue ?? defaultValue
        }
        set {
            storage.set(newValue, forKey: key)
        }
    }

    private let storage: UserDefaults
    private let key: String
    private let defaultValue: Bool

    init(key: String, title: String, defaultValue: Bool, suiteName: String) {
        self.key = key
        self.title = title
        self.defaultValue = defaultValue
        self.storage = UserDefaults(suiteName: suiteName) ?? .standard
    }
}
```

Пример того как это выглядит во ViewController
```swift
let suiteName = "features"

UserDefaultsFeatureToggle(key: "feature_1", title: "Фича 1", defaultValue: true, suiteName: suiteName)
UserDefaultsFeatureToggle(key: "feature_2", title: "Фича 2", defaultValue: true, suiteName: suiteName)
UserDefaultsFeatureToggle(key: "feature_3", title: "Фича 3", defaultValue: true, suiteName: suiteName)
```

**Comment by chausovSurfStudio** [comment]
исправлено в рамках https://github.com/surfstudio/debug-screen-ios/pull/28

**Comment by chausovSurfStudio** [comment]
будет в версии 2.0.0
